spring:
  application:
    name: zipkin-server
  redis:
#    host: hz01-noah-yanzhijie2.hz01.baidu.com
    port: 6379
    database: 10
  rabbitmq:
    addresses: gitlab.igitras.com
  sleuth:
    enabled: false
server:
  port: 8411